/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ProjectsIdSettingsRouteImport } from './routes/projects/$id/settings'
import { Route as ProjectsIdPreferencesRouteImport } from './routes/projects/$id/preferences'
import { Route as ProjectsIdDashboardRouteImport } from './routes/projects/$id/dashboard'
import { Route as ProjectsIdBillingRouteImport } from './routes/projects/$id/billing'
import { Route as ProjectsIdApiKeysRouteImport } from './routes/projects/$id/api-keys'
import { Route as ProjectsIdRecipientsIndexRouteImport } from './routes/projects/$id/recipients/index'
import { Route as ProjectsIdNotificationsIndexRouteImport } from './routes/projects/$id/notifications/index'
import { Route as ProjectsIdRecipientsRecipientIdRouteImport } from './routes/projects/$id/recipients/$recipientId'
import { Route as ProjectsIdNotificationsNotificationIdRouteImport } from './routes/projects/$id/notifications/$notificationId'
import { Route as ProjectsIdBroadcastsBroadcastIdRouteImport } from './routes/projects/$id/broadcasts/$broadcastId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSettingsRoute = ProjectsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdPreferencesRoute = ProjectsIdPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdDashboardRoute = ProjectsIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdBillingRoute = ProjectsIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdApiKeysRoute = ProjectsIdApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdRecipientsIndexRoute =
  ProjectsIdRecipientsIndexRouteImport.update({
    id: '/recipients/',
    path: '/recipients/',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdNotificationsIndexRoute =
  ProjectsIdNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdRecipientsRecipientIdRoute =
  ProjectsIdRecipientsRecipientIdRouteImport.update({
    id: '/recipients/$recipientId',
    path: '/recipients/$recipientId',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdNotificationsNotificationIdRoute =
  ProjectsIdNotificationsNotificationIdRouteImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => ProjectsIdRoute,
  } as any)
const ProjectsIdBroadcastsBroadcastIdRoute =
  ProjectsIdBroadcastsBroadcastIdRouteImport.update({
    id: '/broadcasts/$broadcastId',
    path: '/broadcasts/$broadcastId',
    getParentRoute: () => ProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/projects/$id/billing': typeof ProjectsIdBillingRoute
  '/projects/$id/dashboard': typeof ProjectsIdDashboardRoute
  '/projects/$id/preferences': typeof ProjectsIdPreferencesRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/projects/$id/broadcasts/$broadcastId': typeof ProjectsIdBroadcastsBroadcastIdRoute
  '/projects/$id/notifications/$notificationId': typeof ProjectsIdNotificationsNotificationIdRoute
  '/projects/$id/recipients/$recipientId': typeof ProjectsIdRecipientsRecipientIdRoute
  '/projects/$id/notifications/': typeof ProjectsIdNotificationsIndexRoute
  '/projects/$id/recipients/': typeof ProjectsIdRecipientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/projects/$id/billing': typeof ProjectsIdBillingRoute
  '/projects/$id/dashboard': typeof ProjectsIdDashboardRoute
  '/projects/$id/preferences': typeof ProjectsIdPreferencesRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/projects/$id/broadcasts/$broadcastId': typeof ProjectsIdBroadcastsBroadcastIdRoute
  '/projects/$id/notifications/$notificationId': typeof ProjectsIdNotificationsNotificationIdRoute
  '/projects/$id/recipients/$recipientId': typeof ProjectsIdRecipientsRecipientIdRoute
  '/projects/$id/notifications': typeof ProjectsIdNotificationsIndexRoute
  '/projects/$id/recipients': typeof ProjectsIdRecipientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/projects/$id/billing': typeof ProjectsIdBillingRoute
  '/projects/$id/dashboard': typeof ProjectsIdDashboardRoute
  '/projects/$id/preferences': typeof ProjectsIdPreferencesRoute
  '/projects/$id/settings': typeof ProjectsIdSettingsRoute
  '/projects/$id/broadcasts/$broadcastId': typeof ProjectsIdBroadcastsBroadcastIdRoute
  '/projects/$id/notifications/$notificationId': typeof ProjectsIdNotificationsNotificationIdRoute
  '/projects/$id/recipients/$recipientId': typeof ProjectsIdRecipientsRecipientIdRoute
  '/projects/$id/notifications/': typeof ProjectsIdNotificationsIndexRoute
  '/projects/$id/recipients/': typeof ProjectsIdRecipientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/projects/'
    | '/projects/$id/api-keys'
    | '/projects/$id/billing'
    | '/projects/$id/dashboard'
    | '/projects/$id/preferences'
    | '/projects/$id/settings'
    | '/projects/$id/broadcasts/$broadcastId'
    | '/projects/$id/notifications/$notificationId'
    | '/projects/$id/recipients/$recipientId'
    | '/projects/$id/notifications/'
    | '/projects/$id/recipients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/projects'
    | '/projects/$id/api-keys'
    | '/projects/$id/billing'
    | '/projects/$id/dashboard'
    | '/projects/$id/preferences'
    | '/projects/$id/settings'
    | '/projects/$id/broadcasts/$broadcastId'
    | '/projects/$id/notifications/$notificationId'
    | '/projects/$id/recipients/$recipientId'
    | '/projects/$id/notifications'
    | '/projects/$id/recipients'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/projects/'
    | '/projects/$id/api-keys'
    | '/projects/$id/billing'
    | '/projects/$id/dashboard'
    | '/projects/$id/preferences'
    | '/projects/$id/settings'
    | '/projects/$id/broadcasts/$broadcastId'
    | '/projects/$id/notifications/$notificationId'
    | '/projects/$id/recipients/$recipientId'
    | '/projects/$id/notifications/'
    | '/projects/$id/recipients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/settings': {
      id: '/projects/$id/settings'
      path: '/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof ProjectsIdSettingsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/preferences': {
      id: '/projects/$id/preferences'
      path: '/preferences'
      fullPath: '/projects/$id/preferences'
      preLoaderRoute: typeof ProjectsIdPreferencesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/dashboard': {
      id: '/projects/$id/dashboard'
      path: '/dashboard'
      fullPath: '/projects/$id/dashboard'
      preLoaderRoute: typeof ProjectsIdDashboardRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/billing': {
      id: '/projects/$id/billing'
      path: '/billing'
      fullPath: '/projects/$id/billing'
      preLoaderRoute: typeof ProjectsIdBillingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/api-keys': {
      id: '/projects/$id/api-keys'
      path: '/api-keys'
      fullPath: '/projects/$id/api-keys'
      preLoaderRoute: typeof ProjectsIdApiKeysRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/recipients/': {
      id: '/projects/$id/recipients/'
      path: '/recipients'
      fullPath: '/projects/$id/recipients/'
      preLoaderRoute: typeof ProjectsIdRecipientsIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/notifications/': {
      id: '/projects/$id/notifications/'
      path: '/notifications'
      fullPath: '/projects/$id/notifications/'
      preLoaderRoute: typeof ProjectsIdNotificationsIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/recipients/$recipientId': {
      id: '/projects/$id/recipients/$recipientId'
      path: '/recipients/$recipientId'
      fullPath: '/projects/$id/recipients/$recipientId'
      preLoaderRoute: typeof ProjectsIdRecipientsRecipientIdRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/notifications/$notificationId': {
      id: '/projects/$id/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/projects/$id/notifications/$notificationId'
      preLoaderRoute: typeof ProjectsIdNotificationsNotificationIdRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/broadcasts/$broadcastId': {
      id: '/projects/$id/broadcasts/$broadcastId'
      path: '/broadcasts/$broadcastId'
      fullPath: '/projects/$id/broadcasts/$broadcastId'
      preLoaderRoute: typeof ProjectsIdBroadcastsBroadcastIdRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdApiKeysRoute: typeof ProjectsIdApiKeysRoute
  ProjectsIdBillingRoute: typeof ProjectsIdBillingRoute
  ProjectsIdDashboardRoute: typeof ProjectsIdDashboardRoute
  ProjectsIdPreferencesRoute: typeof ProjectsIdPreferencesRoute
  ProjectsIdSettingsRoute: typeof ProjectsIdSettingsRoute
  ProjectsIdBroadcastsBroadcastIdRoute: typeof ProjectsIdBroadcastsBroadcastIdRoute
  ProjectsIdNotificationsNotificationIdRoute: typeof ProjectsIdNotificationsNotificationIdRoute
  ProjectsIdRecipientsRecipientIdRoute: typeof ProjectsIdRecipientsRecipientIdRoute
  ProjectsIdNotificationsIndexRoute: typeof ProjectsIdNotificationsIndexRoute
  ProjectsIdRecipientsIndexRoute: typeof ProjectsIdRecipientsIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdApiKeysRoute: ProjectsIdApiKeysRoute,
  ProjectsIdBillingRoute: ProjectsIdBillingRoute,
  ProjectsIdDashboardRoute: ProjectsIdDashboardRoute,
  ProjectsIdPreferencesRoute: ProjectsIdPreferencesRoute,
  ProjectsIdSettingsRoute: ProjectsIdSettingsRoute,
  ProjectsIdBroadcastsBroadcastIdRoute: ProjectsIdBroadcastsBroadcastIdRoute,
  ProjectsIdNotificationsNotificationIdRoute:
    ProjectsIdNotificationsNotificationIdRoute,
  ProjectsIdRecipientsRecipientIdRoute: ProjectsIdRecipientsRecipientIdRoute,
  ProjectsIdNotificationsIndexRoute: ProjectsIdNotificationsIndexRoute,
  ProjectsIdRecipientsIndexRoute: ProjectsIdRecipientsIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
