/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ProjectsIdRecipientsRouteImport } from './routes/projects/$id/recipients'
import { Route as ProjectsIdPreferencesRouteImport } from './routes/projects/$id/preferences'
import { Route as ProjectsIdNotificationsRouteImport } from './routes/projects/$id/notifications'
import { Route as ProjectsIdHomeRouteImport } from './routes/projects/$id/home'
import { Route as ProjectsIdBillingRouteImport } from './routes/projects/$id/billing'
import { Route as ProjectsIdApiKeysRouteImport } from './routes/projects/$id/api-keys'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRecipientsRoute = ProjectsIdRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdPreferencesRoute = ProjectsIdPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdNotificationsRoute = ProjectsIdNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdHomeRoute = ProjectsIdHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdBillingRoute = ProjectsIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdApiKeysRoute = ProjectsIdApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/projects/$id/billing': typeof ProjectsIdBillingRoute
  '/projects/$id/home': typeof ProjectsIdHomeRoute
  '/projects/$id/notifications': typeof ProjectsIdNotificationsRoute
  '/projects/$id/preferences': typeof ProjectsIdPreferencesRoute
  '/projects/$id/recipients': typeof ProjectsIdRecipientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/projects/$id/billing': typeof ProjectsIdBillingRoute
  '/projects/$id/home': typeof ProjectsIdHomeRoute
  '/projects/$id/notifications': typeof ProjectsIdNotificationsRoute
  '/projects/$id/preferences': typeof ProjectsIdPreferencesRoute
  '/projects/$id/recipients': typeof ProjectsIdRecipientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/api-keys': typeof ProjectsIdApiKeysRoute
  '/projects/$id/billing': typeof ProjectsIdBillingRoute
  '/projects/$id/home': typeof ProjectsIdHomeRoute
  '/projects/$id/notifications': typeof ProjectsIdNotificationsRoute
  '/projects/$id/preferences': typeof ProjectsIdPreferencesRoute
  '/projects/$id/recipients': typeof ProjectsIdRecipientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/projects/'
    | '/projects/$id/api-keys'
    | '/projects/$id/billing'
    | '/projects/$id/home'
    | '/projects/$id/notifications'
    | '/projects/$id/preferences'
    | '/projects/$id/recipients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/projects'
    | '/projects/$id/api-keys'
    | '/projects/$id/billing'
    | '/projects/$id/home'
    | '/projects/$id/notifications'
    | '/projects/$id/preferences'
    | '/projects/$id/recipients'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/auth/sign-in'
    | '/projects/$id'
    | '/projects/'
    | '/projects/$id/api-keys'
    | '/projects/$id/billing'
    | '/projects/$id/home'
    | '/projects/$id/notifications'
    | '/projects/$id/preferences'
    | '/projects/$id/recipients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/recipients': {
      id: '/projects/$id/recipients'
      path: '/recipients'
      fullPath: '/projects/$id/recipients'
      preLoaderRoute: typeof ProjectsIdRecipientsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/preferences': {
      id: '/projects/$id/preferences'
      path: '/preferences'
      fullPath: '/projects/$id/preferences'
      preLoaderRoute: typeof ProjectsIdPreferencesRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/notifications': {
      id: '/projects/$id/notifications'
      path: '/notifications'
      fullPath: '/projects/$id/notifications'
      preLoaderRoute: typeof ProjectsIdNotificationsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/home': {
      id: '/projects/$id/home'
      path: '/home'
      fullPath: '/projects/$id/home'
      preLoaderRoute: typeof ProjectsIdHomeRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/billing': {
      id: '/projects/$id/billing'
      path: '/billing'
      fullPath: '/projects/$id/billing'
      preLoaderRoute: typeof ProjectsIdBillingRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/api-keys': {
      id: '/projects/$id/api-keys'
      path: '/api-keys'
      fullPath: '/projects/$id/api-keys'
      preLoaderRoute: typeof ProjectsIdApiKeysRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdApiKeysRoute: typeof ProjectsIdApiKeysRoute
  ProjectsIdBillingRoute: typeof ProjectsIdBillingRoute
  ProjectsIdHomeRoute: typeof ProjectsIdHomeRoute
  ProjectsIdNotificationsRoute: typeof ProjectsIdNotificationsRoute
  ProjectsIdPreferencesRoute: typeof ProjectsIdPreferencesRoute
  ProjectsIdRecipientsRoute: typeof ProjectsIdRecipientsRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdApiKeysRoute: ProjectsIdApiKeysRoute,
  ProjectsIdBillingRoute: ProjectsIdBillingRoute,
  ProjectsIdHomeRoute: ProjectsIdHomeRoute,
  ProjectsIdNotificationsRoute: ProjectsIdNotificationsRoute,
  ProjectsIdPreferencesRoute: ProjectsIdPreferencesRoute,
  ProjectsIdRecipientsRoute: ProjectsIdRecipientsRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
